### ISSUE TITLE
Terminal with the color Purple.

### ISSUE THREAD

**Issue by Initu-Castilhos** [Muqtxdir/yaru-remix#10]
The terminal has a purple background that doesn't match the theme.

**Comment by Muqtxdir** [comment]
Hi @Initu-Castilhos,

So based on the suggestion, I've modified the`$_terminal_bg_color`  and `$terminal_fg_color` for ***Terminal-app*** . See the _**screenshots**_ below and let me know if need further color-refinement ?

### yaru-remix:
![Screenshot from 2021-03-08 19-01-07](https://user-images.githubusercontent.com/54065734/110328199-0af52680-8041-11eb-841d-c04dbe982f2d.png)

### yaru-remix-light:
![Screenshot from 2021-03-08 19-01-23](https://user-images.githubusercontent.com/54065734/110328241-1b0d0600-8041-11eb-84dd-3f8e35803818.png)

### yaru-remix-dark:
![Screenshot from 2021-03-08 19-01-31](https://user-images.githubusercontent.com/54065734/110328267-25c79b00-8041-11eb-9531-f5da97faca80.png)
