### ISSUE TITLE
Dark inherit Humanity-Dark icon theme.

### ISSUE THREAD

**Issue by Initu-Castilhos** [Muqtxdir/yaru-remix#11]
The Yaru-remix-dark icon theme inherits the Humanity-Dark icons for use in Mate and XFCE.
![Captura de tela de 2021-03-05 18-54-52](https://user-images.githubusercontent.com/59381215/110177908-755d5b00-7de4-11eb-8211-ccee8c61e806.png)

**Comment by Muqtxdir** [comment]
Thanks @Initu-Castilhos  for noticing this, I'll change this for next release 👍

**Comment by Muqtxdir** [comment]
hi @Initu-Castilhos,

I am making changes for the next-release on `gnome-3-38` and I've corrected it there with latest commit :
https://github.com/Muqtxdir/yaru-remix/blob/6846ef78d604b3630e902562f600cf06df2738aa/icons/Yaru-remix-dark/index.theme#L4 

I'll keep this **issue** open to keep it as reminder to make the following changes in `gnome-40`, `gnome-3-36 (Ubuntu 20.04 LTS)`, `gnome-3-28 (Ubuntu 18.04 LTS) `
