### ISSUE TITLE
Lighter dark theme

### ISSUE THREAD

**Issue by Trikenstein** [Muqtxdir/yaru-remix#13]
The dark version (as of 2021-03-10) is almost black. Working on the evening with several overlapping windows, then it become straining on the eyes because all separate windows seems to merge together in a big dark mass. The Gnome terminal with several tabs also becomes hard to use because the current tab doesn't stand out enough.

Here are some example of lighter dark GTK themes which avoid this issue:

- Nordic https://www.gnome-look.org/p/1267246/
- Arc-Dark-Solarized https://www.gnome-look.org/p/1315893/
- Cameo-Alu-Dark-Traditional  https://www.gnome-look.org/p/1397841/

Please also use shadow effects around the border to make the windows in focus standout better. I would even say maybe use a white shadow?

Special requests. Maybe you have already implemented these designs, just make sure to keep those.

1. Make the windows control buttons a bit bigger and more meaningful (+-X). Please refrain from imitating the macOS design. I own a mackbook pro but somehow I  find those mac colored buttons really confusing.
2. Make titlebar compact

**Comment by Muqtxdir** [comment]
Hi @Trikenstein,

I too have noticed that the dark-theme is indeed a lot darker but ignored to properly test it for the contrast and readbility as I mostly prefer using the default and light theme and rarely switch to dark-theme. That's surely a mistake on my part, I should have done prior testing before pushing for a release 
> Here are some example of lighter dark GTK themes which avoid this issue:
 > - Nordic https://www.gnome-look.org/p/1267246/
> - Arc-Dark-Solarized https://www.gnome-look.org/p/1315893/
> - Cameo-Alu-Dark-Traditional  https://www.gnome-look.org/p/1397841/

thanks for sharing these themes(fan of Nordic theme) but am I allowed to use their color palette as a reference?

> Special requests. Maybe you have already implemented these designs, just make sure to keep those.
> 1. Make the windows control buttons a bit bigger and more meaningful (+-X). Please refrain from imitating the macOS design. I own a mackbook pro but somehow I find those mac colored buttons really confusing.

It's always welcome to pass suggestions here, I don't plan on switching the window buttons to macOS like for yaru-remix 
I'll looked into getting the buttons biggers but I'm afraid that'll make the headerbars even bigger 

>Make titlebar compact

I could do that but the issues stated here will come into play so I decline to make it compact (I hope you understand) : [#2360](https://github.com/ubuntu/yaru/issues/2360)

So, I'll start redoing dark theme for Gnome shell first then the gtk3 and gtk4 theme. It'll take time so can't say it'll happen soon (sorry again)

If I am misinterpreting or missing something in this issue description, please elaborate it a little more in detail if I got it wrong (what can I say, I'm dumb sometimes)

and lastly a big thank you for taking time and reporting an issue here

**Comment by Trikenstein** [comment]
Hi,

I have no idea about the relationship of the compact titlebar with the issue #2360 [Default padding is not on par with custom styled button](https://github.com/ubuntu/yaru/issues/2360). If there is, personally I still prefer having a compact titlebar and having that padding issue, which I don't think is important.

> am I allowed to use their color palette as a reference?

This is the beauty of open source. The Nordic author mention in his [github readme](https://github.com/EliverLara/Nordic): 

> Nordic is a Gtk3.20+ theme created using the awesome [Nord color pallete](https://github.com/arcticicestudio/nord)

**Another suggestion/request:**

- In Gnome terminal with multiple tabs: can you make sure the tab in focus stand out better? In addition to the blue underline, can you make the background of the tab to be different? Can you play around with [Nordic theme](https://www.gnome-look.org/p/1267246/) to see how this is addressed. The screenshot below show how the terminal tabs look in Yaru Remix

![YaruRemix-TerminalTabs-notStandout-enough](https://user-images.githubusercontent.com/72353094/110868273-49cfea00-8296-11eb-9611-f8beb199e2cc.png)

**Comment by Trikenstein** [comment]
The same terminal under Nordic theme. Slightly better but not really well done

![Nordic-TerminalTabs](https://user-images.githubusercontent.com/72353094/110868872-5dc81b80-8297-11eb-9777-49eaac5ef1ff.png)

**Comment by Muqtxdir** [comment]
Hi @Trikenstein,

Sorry for the late-reply :(

> In Gnome terminal with multiple tabs: can you make sure the tab in focus stand out better? In addition to the blue underline, can you make the background of the tab to be different? Can you play around with Nordic theme to see how this is addressed. The screenshot below show how the terminal tabs look in Yaru Remix

I could do that but won't because including this will further deviate **Yaru-remix** from **Yaru** ( _I am trying to be as close to upstream yaru with fewer modifications_ ). 

Was free this weekend so tried to lighten the dark-theme based on **_yaru's-palette_** according to your input. Download and try the dark-theme from the [compressed-tar-file](https://github.com/Muqtxdir/yaru-remix/releases/download/v20.04/yaru-remix-alternate-20.04.tar.xz) and share your experience

**Comment by Trikenstein** [comment]
Hi,

Thanks for the preview. It is slightly lighter. In my opinion, it is better than the previous darker version. I suppose it should be usable for most of users. The issue I raised here was more of a request than a real issue. Because it is mostly a matter of personal preference. 

> I am trying to be as close to upstream yaru with fewer modifications 

In this case, there is no need to do anything further.
