### ISSUE TITLE
Can't see calendar numbers

### ISSUE THREAD

**Issue by shemgp** [Muqtxdir/yaru-remix#14]
![calendar color bug](https://user-images.githubusercontent.com/1734126/111624911-3a691780-8827-11eb-876a-f137dfee4b92.png)

As you can see from the screenshot, the week days calendar numbers can't be seen because they're white. This is on hirsute with mostly GNOME 40.beta packages.

**Comment by Muqtxdir** [comment]
Hi @shemgp,

> As you can see from the screenshot, the week days calendar numbers can't be seen because they're white

Thanks for reporting this, I've identified what's causing this behaviour in calendar-menu. I''ll make changes to the `gnome-40`, `gnome-3-38` branch tomorrow after testing it today.

> This is on hirsute with mostly GNOME 40.beta packages

could you share with me the process to get GNOME 40 on `hirsute` (_ubuntu 21.04_). Thanks in advance!

**Comment by shemgp** [comment]
> could you share with me the process to get GNOME 40 on `hirsute` (_ubuntu 21.04_). Thanks in advance!

I packaged most of GNOME 40.beta apps that can be easily done in [this test PPA](https://launchpad.net/~shemgp/+archive/ubuntu/gnome).

**Comment by Muqtxdir** [comment]
> I packaged most of GNOME 40.beta apps that can be easily done in this test PPA.

@shemgp  this is amazing stuff, If it's all good I'll switch from **Fedora 34 beta** to **Ubuntu 21.04**. I'll also try to generate `gnome-shell-theme.gresource` for gdm3 for this.

I have a couple questions before trying your PPA:
**_Question 1_***: Is it beta-ish stable or does it crashes often?
**_Question 2_***: Are you using **Yaru** theme or is it a default gnome-shell experience?
**_Question 1_***: Is wayland the default session or Xorg?

**Comment by shemgp** [comment]
> **_Question 1_**_: Is it beta-ish stable or does it crashes often? 
Using it as a nightly driver and haven't seen it crash yet. Missing some extensions though: eg. dash-to-dock. My work machine, which is on focal gnome-shell 3.38, is crashing more than this.

> **_Question 2_**_: Are you using **Yaru** theme or is it a default gnome-shell experience?
I could not use **Yaru** since it's [not compatible with GNOME 40 yet](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3771). I'm using GNOME session, which can be changed when logging in in GDM3.

> **_Question 1_***: Is wayland the default session or Xorg?
I quickly disabled Wayland in /etc/gdm3/custom.conf, since I might be using some extensions that didn't work there. So I haven't tested Wayland yet.

Just FYI, this PPA is not officially supported by Canonical/Ubuntu developers. It's just me trying to test GNOME 40 in hirsute.

**Comment by Muqtxdir** [comment]
Thank you @shemgp for answering my questions. I don't use much of the extensions so that won't be a problem for me. 

> Just FYI, this PPA is not officially supported by Canonical/Ubuntu developers. It's just me trying to test GNOME 40 in hirsute.

I understood this when you shared your PPA, but thanks again for clarifying.
Now of to firing a `hirsute` in gnome-boxes

**Comment by Muqtxdir** [comment]
I've pushed the changes @shemgp could you try installing now again from `gnome-40` branch and check whether it is solved?

**Comment by shemgp** [comment]
I can confirm that it's already fix. Thanks for the quick response!
