### ISSUE TITLE
No way to uninstall?

### ISSUE THREAD

**Issue by shivendra90** [Muqtxdir/yaru-remix#18]
How do you remove the theme if installed from the shell script?

**Comment by Muqtxdir** [comment]
Hi @shivendra90,

This linked [document](https://github.com/Muqtxdir/yaru-remix/blob/master/script.md#uninstallation-using-script) covers the steps to uninstall ***yaru-remix*** using `uninstall.sh` script 

If the instructions still don't seem clear, you can bring the issues here in this thread

**Comment by shivendra90** [comment]
@Muqtxdir Thanks!
