### ISSUE TITLE
Not visibles calendar dates in Yaru-remix-light with fix included

### ISSUE THREAD

**Issue by Michedev** [Muqtxdir/yaru-remix#4]
Using:
```
                   -`                    mikedev@root 
                  .o+`                   ------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  
               `+oooooo:                 Kernel: 5.9.8-arch1-1 
               -+oooooo+:                Uptime: 4 hours, 10 mins 
             `/:-:++oooo+:                
            `/++++/+++++++:              Shell: fish 3.1.2 
           `/++++++++++++++:             Resolution: 2560x1440 
          `/+++ooooooooooooo/`           DE: GNOME 3.38.1 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Yaru-remix-light 
       -osssssso.      :ssssssso.        Theme: Desert [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Zafiro-Icons-Light [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: terminator 
   `/ossssso+/:-        -:/+osssso+-      
  `+sso+:-`                 `.-/+oso:    GPU: Intel HD Graphics 620 


```

My problem is very simple: in my calendar dates with activities were not visible. Therefore I've navigated through the gnome shell css code and I've found that there was a missing _color_ property inside calendar class. To be more exact the right point was:
--->  .calendar .calendar-day-with-events {
    color: rgb(124, 65, 65);

I'm not doing a pull request because I'm not the theme author, therefore I don't know the right color to put there, just wanted to signal this!

**Comment by Muqtxdir** [comment]
hi @Michedev,

Thanks for taking your time to report the issue, can you post a screenshot for this? 

here's my calendar with events:
![calendar-events](https://user-images.githubusercontent.com/54065734/100117767-26c22b80-2e9b-11eb-81b9-e2faeaecc788.png)

**Comment by Michedev** [comment]
No I mean the day number of the month is unreadable! I've darken a little bit the calendar card so the white is a little bit visible, with default theme would be invisible.

Without my fix:

![Screenshot from 2020-11-24 17-14-09](https://user-images.githubusercontent.com/12683228/100120810-a8549200-2e78-11eb-905b-bc7f734c34c2.png)

With my fix (code down left):

![Screenshot from 2020-11-24 17-14-30](https://user-images.githubusercontent.com/12683228/100120806-a7bbfb80-2e78-11eb-99c5-2a247f2af4b5.png)

**Comment by Muqtxdir** [comment]
thanks @Michedev for explaining it clearly

>I'm not doing a pull request because I'm not the theme author, therefore I don't know the right color to put there, just wanted to signal this!

If you want to do a pull request, what do you think about the color: #315bef ?

**Comment by Michedev** [comment]
it is applied from gnome-look.
The color is good, also coherent with the rest of the calendar. I will do a pull request in the next minutes!
I've found another problem and eventually a fix, basically when I click into other dates outside today the blue circle didn't appear. It is intended in this way or not?

**Comment by Muqtxdir** [comment]
Could you apply the theme from GitHub before the PR? ( I think this is was rectified with 20.10)

**Comment by Michedev** [comment]
Unfortunately no 

![Screenshot from 2020-11-24 18-08-10](https://user-images.githubusercontent.com/12683228/100128135-308a6580-2e80-11eb-8220-0d9ed52967fb.png)

**Comment by Muqtxdir** [comment]
ok 
 >I will do a pull request in the next minutes!

Looking forward to it @Michedev! while you change it for Yaru-remix light, could you do the same for standard and dark gnome-shell themes
>when I click into other dates outside today the blue circle didn't appear. It is intended in this way or not?

yes,its intentionally like that
it's inherited from Yaru so I want to keep it as close to Yaru-style

**Comment by Muqtxdir** [comment]
Thanks for the PR @Michedev 
I'll update the themes on gnome-look.org when I'm free until then I'll keep this issue open as a reminder

**Comment by Muqtxdir** [comment]
hi,
upon trying the theme from the master, the hover on calenadar today is not readable
![after](https://user-images.githubusercontent.com/54065734/100217957-1319d200-2f3a-11eb-8ab8-e3fb987d77c8.gif)
Does this happen to you as well, @Michedev ?
