### ISSUE TITLE
Uninstall script makes Pop!_OS 20.10 crash before login screen.

### ISSUE THREAD

**Issue by DevMatar** [Muqtxdir/yaru-remix#7]
Installed on Pop!_OS 20.10 stock and everything worked fine but when I decided to uninstall using the provided script and restarted the system, I was greeted with this:
![ohno](https://user-images.githubusercontent.com/72623880/104808362-7ff96c00-5807-11eb-98bb-9153cd10b955.jpg)

I am not a techie by any means so for now, I fixed it by going into tty by pressing ctrl + alt + f3 and reinstalled the theme. It fixed the login issue but the problem of being unable to uninstall still persists so I cannot change/remove this theme.

**Comment by Muqtxdir** [comment]
hi @DevMatar,

thanks for taking your time to report the issue regarding the `uninstall.sh` script, it seems that from your description the Yaru-remix files were removed but the script did not change it back to the default Pop!_OS theme
can you tell me whether the script ran completely till the end? or am I missing something ?

down below, is a screenrecorded GIF done by [Peek](https://flathub.org/apps/details/com.uploadedlobster.peek) of `uninstall.sh` script on my Pop!_OS 20.10 install

![Peek 2021-01-16 17-35](https://user-images.githubusercontent.com/54065734/104811549-5a2d9080-5822-11eb-9397-66c1a893e1c7.gif)

**Comment by DevMatar** [comment]
Yes, the script ran completely without any errors. I again uninstalled and took a screen cast:
![Peek 2021-01-16 19-40](https://user-images.githubusercontent.com/72623880/104816222-7c7fd800-583b-11eb-93cc-e49e9b7e9599.gif)
Again, after I restarted, I was greeted with the same "Something has gone wrong" Screen.

Here are my system specs if they might help out with something:
![image](https://user-images.githubusercontent.com/72623880/104816314-2b241880-583c-11eb-8220-660cca51fb3c.png)

**Comment by DevMatar** [comment]
Alright so I re downloaded the uninstallation script and reran it and it worked fine this time. I checked the previous uninstallation script and found out that it did not have the following lines:

```
if  [ $(lsb_release -is) == "Pop" ]; then
sudo update-alternatives --quiet --install /usr/share/gnome-shell/gdm3-theme.gresource gdm3-theme.gresource /usr/share/gnome-shell/theme/Pop/gnome-shell-theme.gresource 15
sudo update-alternatives --quiet --set gdm3-theme.gresource /usr/share/gnome-shell/theme/Pop/gnome-shell-theme.gresource
echo  '  [ * ] Applied default Pop!_OS gdm3 theme.'
fi
```

So, I think I downloaded an old script (although don't know how because I remember downloading from github and firefox download history shows the same). But the problem is fixed now and the uninstallation script is fine. Thanks for your help.

**Comment by Muqtxdir** [comment]
> But the problem is fixed now and the uninstallation script is fine. Thanks for your help.

I'm glad that the uninstall script is working for you, I think I need to update the scripts present in gnome-look.org ( I'll do it soon)
