### ISSUE TITLE
May I publish the light and dark varaints on flathub?

### ISSUE THREAD

**Issue by Mek101** [Muqtxdir/yaru-remix#9]
I'm currently working on the manifest

**Comment by Muqtxdir** [comment]
Hi @Mek101,

Thanks for considering do this but I've already published themes for all the variants, you can see the links below of their flathub GitHub repositories:
- [Yaru-remix-light](https://github.com/flathub/org.gtk.Gtk3theme.Yaru-remix-light)
- [Yaru-remix-dark](https://github.com/flathub/org.gtk.Gtk3theme.Yaru-remix-dark)
- [Yaru-remix](https://github.com/flathub/org.gtk.Gtk3theme.Yaru-remix)

Or am I misinterpreting something else for this?

**Comment by Mek101** [comment]
Woops, sorry. For some reason they didn't show up in `flatpak search` when I searched yesteday

**Comment by Muqtxdir** [comment]
@Mek101, if you are interested and have some spare-time, could you try to get the [yaru-colors](https://github.com/Jannomag/Yaru-Colors) themes on flathub ?

**Comment by Mek101** [comment]
Thanks for the direction, I will check it out
